### Q1. Multiply all values in given dictionary and print it.

In [1]:
my_dict = {'a':2,'b':3,'c':4}

# Implement me

24


### Q2. Create and print a dictionary from list of lists where one list values act as key and corresponding value from another list act as value

In [2]:
country_name = ["US", "Russia", "Japan", "Germany","Canada"]
capital_city = ["Washington,DC", "Moscow", "Tokyo", "Berlin","Toronto"]

# Implement me

{'US': 'Washington,DC', 'Russia': 'Moscow', 'Japan': 'Tokyo', 'Germany': 'Berlin', 'Canada': 'Toronto'}


### Q3. Print the elements which are not common between the two lists

In [3]:
list1 = [1, 2, 1, 3, 4]
list2 = [1, 2, 5]

# Implement me

[3, 4, 5]


### Q4. Sort lists present as values in a dictionary and print the sorted dictionary

In [4]:
num = {'l1': [30, 10], 'l2': [50, 10, 20], 'l3': [30, 20, 40, 10]}

# Implement me

{'l1': [10, 30], 'l2': [10, 20, 50], 'l3': [10, 20, 30, 40]}


### Q5. Concatenate the following dictionaries and print the newly created one

In [5]:
dic_1={'a':1, 'b':2}
dic_2={'c':3, 'd':4}
dic_3={'e':5,'f':6}

# Implement me

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}


### Q6. Print all unique values (not the keys) from a list of dictionaries.

In [6]:
my_list = [{"A":"1"}, {"A": "2"}, {"B": "1"}, {"B": "5"}, {"C":"5"}, {"A":"9"},{"D":"7"}]

# Implement me

['1', '2', '5', '9', '7']


### Q7. Find and print common key-value pair in given two dictionaries.

In [7]:
x = {'1': 1, '2': 2, '3': 2}
y = {'1': 1, '2': 2, '3': 3, '4': 4}

# Implement me

{'1': 1, '2': 2}


### Q8. Convert below 2-D array to a single dimension (1XN) array.

In [8]:
import numpy as np

x = np.array([[10, 20, 30], [40, 50,60]])

# Implement me

[10 20 30 40 50 60]


### Q9. Write a Python program to convert below 1-D array to 2-D (NxN) array.

In [9]:
x = np.array([0,1,2,3,4,5,6,7,8])

x = x.reshape(3, -1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Q10. Write a program which can find even numbers in a list by using filter function. 

In [10]:
li = [1,2,3,4,5,6,7,8,9,10]

# Implement me

[2, 4, 6, 8, 10]


### Q11. Write a program to make a list whose elements are square of even number in given list.

Hint : You can use lambda function

In [11]:
li = [1,2,3,4,5,6,7,8,9,10]

# Implement me

[4, 16, 36, 64, 100]


# Reference 
Exercises used here are taken from:
https://www.w3resource.com/python-exercises/